package com.enterprise.upload.model.enums;
public enum RuleType {
    COLUMN_EXISTS, COLUMN_TYPE, ROW_COUNT_MIN, ROW_COUNT_MAX,
    NOT_NULL, NOT_EMPTY, MAX_NULL_PERCENT,
    UNIQUE, UNIQUE_COMPOSITE,
    REGEX_MATCH, DATE_FORMAT, ALLOWED_VALUES, EMAIL_FORMAT, PHONE_FORMAT,
    TAX_CODE_FORMAT, ACCOUNT_NUMBER_FORMAT,
    RANGE_MIN, RANGE_MAX, RANGE_BETWEEN, DATE_RANGE, DATE_NOT_FUTURE, DATE_NOT_PAST,
    FOREIGN_KEY, CROSS_TABLE_SUM,
    CUSTOM_SQL, CUSTOM_PYTHON
}
